version: '3.8'

services:
  # Backend service
  server:
    build: ./server
    container_name: task-manager-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - task-manager-network

  # Frontend service
  client:
    build: ./client
    container_name: task-manager-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge